# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/system_ACF_AXI_mini_0_0.xci
# IP: The module: 'system_ACF_AXI_mini_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/myHWCorrelator_PL_top_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myHWCorrelator_PL_top_0 || ORIG_REF_NAME==myHWCorrelator_PL_top_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/c_counter_binary_0/c_counter_binary_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_0 || ORIG_REF_NAME==c_counter_binary_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/xbip_multadd_0/xbip_multadd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_multadd_0 || ORIG_REF_NAME==xbip_multadd_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/dual_port_acf_bram/dual_port_acf_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dual_port_acf_bram || ORIG_REF_NAME==dual_port_acf_bram} -quiet] -quiet

# XDC: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/dual_port_acf_bram/dual_port_acf_bram_ooc.xdc

# IP: C:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/system_ACF_AXI_mini_0_0.xci
# IP: The module: 'system_ACF_AXI_mini_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/myHWCorrelator_PL_top_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myHWCorrelator_PL_top_0 || ORIG_REF_NAME==myHWCorrelator_PL_top_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/c_counter_binary_0/c_counter_binary_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_0 || ORIG_REF_NAME==c_counter_binary_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/fifo_generator_0/fifo_generator_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/xbip_multadd_0/xbip_multadd_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_multadd_0 || ORIG_REF_NAME==xbip_multadd_0} -quiet] -quiet

# IP: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/dual_port_acf_bram/dual_port_acf_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dual_port_acf_bram || ORIG_REF_NAME==dual_port_acf_bram} -quiet] -quiet

# XDC: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/myHWCorrelator_PL_top_0/src/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/nc1220/xilinx_workspace/dvd_firmware/dvd_firmware.srcs/sources_1/bd/system/ip/system_ACF_AXI_mini_0_0/src/dual_port_acf_bram/dual_port_acf_bram_ooc.xdc
